
import React from 'react';

const Footer: React.FC = () => {
    return (
        <footer className="text-center p-8 mt-16 border-t border-gray-700">
            <p className="text-gray-500">Page generated by Gemini.</p>
        </footer>
    );
};

export default Footer;
